name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: |
          pip install hatch
          hatch build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  pypi-publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Retrieve packages
      uses: actions/download-artifact@v4
    - name: Upload packages
      uses: pypa/gh-action-pypi-publish@release/v1
